-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_opt4_fir_opt4_Pipeline_TDL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fir_opt4_fir_opt4_Pipeline_TDL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv11_2B : STD_LOGIC_VECTOR (10 downto 0) := "00000101011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln73_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_1_reg_345 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_reg_345_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_345_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_345_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_345_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_345_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_345_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_345_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_fu_189_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_reg_356_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_reg_361 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_reg_361_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln71_fu_219_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln71_reg_366 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln71_reg_366_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_reg_372 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln74_fu_256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln75_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln71_fu_288_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_56 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_316_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_294_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_167_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_183_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln71_fu_203_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln71_fu_203_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln71_fu_203_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_183_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln74_fu_223_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln74_fu_232_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln74_fu_232_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln74_fu_232_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln75_fu_265_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln75_fu_265_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln75_fu_265_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_271_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_294_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_316_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln71_fu_203_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln74_fu_232_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln75_fu_265_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_294_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_294_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_294_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_316_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component fir_opt4_urem_5ns_3ns_2_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component fir_opt4_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component fir_opt4_sparsemux_7_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_opt4_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_5ns_3ns_2_9_1_U1 : component fir_opt4_urem_5ns_3ns_2_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_sig_allocacmp_i_1,
        din1 => grp_fu_183_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_183_p2);

    mul_5ns_7ns_11_1_1_U2 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln71_fu_203_p0,
        din1 => mul_ln71_fu_203_p1,
        dout => mul_ln71_fu_203_p2);

    mul_5ns_7ns_11_1_1_U3 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln74_fu_232_p0,
        din1 => mul_ln74_fu_232_p1,
        dout => mul_ln74_fu_232_p2);

    mul_5ns_7ns_11_1_1_U4 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln75_fu_265_p0,
        din1 => mul_ln75_fu_265_p1,
        dout => mul_ln75_fu_265_p2);

    sparsemux_7_2_16_1_1_U5 : component fir_opt4_sparsemux_7_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 16,
        CASE1 => "10",
        din1_WIDTH => 16,
        CASE2 => "00",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        din1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        din2 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1,
        def => tmp_fu_294_p7,
        sel => trunc_ln71_reg_366_pp0_iter9_reg,
        dout => tmp_fu_294_p9);

    sparsemux_7_2_16_1_1_U6 : component fir_opt4_sparsemux_7_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 16,
        CASE1 => "00",
        din1_WIDTH => 16,
        CASE2 => "01",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        din1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        din2 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1,
        def => tmp_1_fu_316_p7,
        sel => trunc_ln71_reg_366_pp0_iter9_reg,
        dout => tmp_1_fu_316_p9);

    flow_control_loop_pipe_sequential_init_U : component fir_opt4_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln73_fu_177_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_56 <= add_ln75_fu_189_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_56 <= ap_const_lv5_1F;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln75_reg_356 <= add_ln75_fu_189_p2;
                add_ln75_reg_356_pp0_iter1_reg <= add_ln75_reg_356;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_1_reg_345 <= ap_sig_allocacmp_i_1;
                i_1_reg_345_pp0_iter1_reg <= i_1_reg_345;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln75_reg_356_pp0_iter2_reg <= add_ln75_reg_356_pp0_iter1_reg;
                add_ln75_reg_356_pp0_iter3_reg <= add_ln75_reg_356_pp0_iter2_reg;
                add_ln75_reg_356_pp0_iter4_reg <= add_ln75_reg_356_pp0_iter3_reg;
                add_ln75_reg_356_pp0_iter5_reg <= add_ln75_reg_356_pp0_iter4_reg;
                add_ln75_reg_356_pp0_iter6_reg <= add_ln75_reg_356_pp0_iter5_reg;
                add_ln75_reg_356_pp0_iter7_reg <= add_ln75_reg_356_pp0_iter6_reg;
                add_ln75_reg_356_pp0_iter8_reg <= add_ln75_reg_356_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383 <= zext_ln74_fu_256_p1(4 - 1 downto 0);
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377 <= zext_ln74_fu_256_p1(4 - 1 downto 0);
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389 <= zext_ln74_fu_256_p1(4 - 1 downto 0);
                i_1_reg_345_pp0_iter2_reg <= i_1_reg_345_pp0_iter1_reg;
                i_1_reg_345_pp0_iter3_reg <= i_1_reg_345_pp0_iter2_reg;
                i_1_reg_345_pp0_iter4_reg <= i_1_reg_345_pp0_iter3_reg;
                i_1_reg_345_pp0_iter5_reg <= i_1_reg_345_pp0_iter4_reg;
                i_1_reg_345_pp0_iter6_reg <= i_1_reg_345_pp0_iter5_reg;
                i_1_reg_345_pp0_iter7_reg <= i_1_reg_345_pp0_iter6_reg;
                tmp_3_reg_361 <= mul_ln71_fu_203_p2(10 downto 7);
                tmp_3_reg_361_pp0_iter9_reg <= tmp_3_reg_361;
                tmp_4_reg_372 <= mul_ln74_fu_232_p2(10 downto 7);
                trunc_ln71_reg_366 <= trunc_ln71_fu_219_p1;
                trunc_ln71_reg_366_pp0_iter9_reg <= trunc_ln71_reg_366;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln74_fu_223_p2 <= std_logic_vector(unsigned(i_1_reg_345_pp0_iter7_reg) + unsigned(ap_const_lv5_1F));
    add_ln75_fu_189_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv5_1E));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln73_fu_177_p2)
    begin
        if (((icmp_ln73_fu_177_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv5_1F;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_56;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln71_reg_366_pp0_iter9_reg, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383, ap_block_pp0_stage0, zext_ln71_fu_288_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383;
            elsif ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= zext_ln71_fu_288_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln71_reg_366, zext_ln74_fu_256_p1, ap_block_pp0_stage0, zext_ln75_fu_281_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln71_reg_366 = ap_const_lv2_0)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= zext_ln75_fu_281_p1(4 - 1 downto 0);
            elsif ((trunc_ln71_reg_366 = ap_const_lv2_2)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= zext_ln74_fu_256_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln71_reg_366_pp0_iter9_reg)
    begin
        if (((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln71_reg_366)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln71_reg_366 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln71_reg_366 = ap_const_lv2_2)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln71_reg_366_pp0_iter9_reg, ap_block_pp0_stage0, tmp_1_fu_316_p9, tmp_fu_294_p9)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local <= tmp_1_fu_316_p9;
            elsif ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local <= tmp_fu_294_p9;
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln71_reg_366_pp0_iter9_reg)
    begin
        if (((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln71_reg_366_pp0_iter9_reg, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377, ap_block_pp0_stage0, zext_ln71_fu_288_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= zext_ln71_fu_288_p1(4 - 1 downto 0);
            elsif ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377;
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln71_reg_366, zext_ln74_fu_256_p1, ap_block_pp0_stage0, zext_ln75_fu_281_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln71_reg_366 = ap_const_lv2_2)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= zext_ln75_fu_281_p1(4 - 1 downto 0);
            elsif ((trunc_ln71_reg_366 = ap_const_lv2_1)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= zext_ln74_fu_256_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln71_reg_366_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln71_reg_366)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln71_reg_366 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln71_reg_366 = ap_const_lv2_2)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln71_reg_366_pp0_iter9_reg, ap_block_pp0_stage0, tmp_1_fu_316_p9, tmp_fu_294_p9)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local <= tmp_fu_294_p9;
            elsif ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local <= tmp_1_fu_316_p9;
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln71_reg_366_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln71_reg_366_pp0_iter9_reg, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389, ap_block_pp0_stage0, zext_ln71_fu_288_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= zext_ln71_fu_288_p1(4 - 1 downto 0);
            elsif ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389;
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln71_reg_366, zext_ln74_fu_256_p1, ap_block_pp0_stage0, zext_ln75_fu_281_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln71_reg_366 = ap_const_lv2_1)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= zext_ln75_fu_281_p1(4 - 1 downto 0);
            elsif ((trunc_ln71_reg_366 = ap_const_lv2_0)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= zext_ln74_fu_256_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln71_reg_366_pp0_iter9_reg)
    begin
        if (((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln71_reg_366)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln71_reg_366 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln71_reg_366 = ap_const_lv2_0)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln71_reg_366_pp0_iter9_reg, ap_block_pp0_stage0, tmp_1_fu_316_p9, tmp_fu_294_p9)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local <= tmp_fu_294_p9;
            elsif ((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local <= tmp_1_fu_316_p9;
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln71_reg_366_pp0_iter9_reg)
    begin
        if (((not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)) and not((trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln71_reg_366_pp0_iter9_reg = ap_const_lv2_0)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_183_p1 <= ap_const_lv5_3(3 - 1 downto 0);
    icmp_ln73_fu_177_p2 <= "1" when (tmp_2_fu_167_p4 = ap_const_lv4_0) else "0";
    mul_ln71_fu_203_p0 <= mul_ln71_fu_203_p00(5 - 1 downto 0);
    mul_ln71_fu_203_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_345_pp0_iter7_reg),11));
    mul_ln71_fu_203_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    mul_ln74_fu_232_p0 <= mul_ln74_fu_232_p00(5 - 1 downto 0);
    mul_ln74_fu_232_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_fu_223_p2),11));
    mul_ln74_fu_232_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    mul_ln75_fu_265_p0 <= mul_ln75_fu_265_p00(5 - 1 downto 0);
    mul_ln75_fu_265_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln75_reg_356_pp0_iter8_reg),11));
    mul_ln75_fu_265_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    tmp_1_fu_316_p7 <= "XXXXXXXXXXXXXXXX";
    tmp_2_fu_167_p4 <= ap_sig_allocacmp_i_1(4 downto 1);
    tmp_5_fu_271_p4 <= mul_ln75_fu_265_p2(10 downto 7);
    tmp_fu_294_p7 <= "XXXXXXXXXXXXXXXX";
    trunc_ln71_fu_219_p1 <= grp_fu_183_p2(2 - 1 downto 0);
    zext_ln71_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_361_pp0_iter9_reg),64));
    zext_ln74_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_372),64));
    zext_ln75_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_271_p4),64));
end behav;
