// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_opt4_fir_opt4_Pipeline_TDL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0;
output  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0;
output  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0;
output  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln73_fu_177_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_1_reg_345;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] i_1_reg_345_pp0_iter1_reg;
reg   [4:0] i_1_reg_345_pp0_iter2_reg;
reg   [4:0] i_1_reg_345_pp0_iter3_reg;
reg   [4:0] i_1_reg_345_pp0_iter4_reg;
reg   [4:0] i_1_reg_345_pp0_iter5_reg;
reg   [4:0] i_1_reg_345_pp0_iter6_reg;
reg   [4:0] i_1_reg_345_pp0_iter7_reg;
wire   [4:0] add_ln75_fu_189_p2;
reg   [4:0] add_ln75_reg_356;
reg   [4:0] add_ln75_reg_356_pp0_iter1_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter2_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter3_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter4_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter5_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter6_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter7_reg;
reg   [4:0] add_ln75_reg_356_pp0_iter8_reg;
reg   [3:0] tmp_3_reg_361;
reg   [3:0] tmp_3_reg_361_pp0_iter9_reg;
wire   [1:0] trunc_ln71_fu_219_p1;
reg   [1:0] trunc_ln71_reg_366;
reg   [1:0] trunc_ln71_reg_366_pp0_iter9_reg;
reg   [3:0] tmp_4_reg_372;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389;
wire   [63:0] zext_ln74_fu_256_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln75_fu_281_p1;
wire   [63:0] zext_ln71_fu_288_p1;
reg   [4:0] i_fu_56;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local;
wire   [15:0] tmp_1_fu_316_p9;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local;
wire   [15:0] tmp_fu_294_p9;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local;
wire   [3:0] tmp_2_fu_167_p4;
wire   [2:0] grp_fu_183_p1;
wire   [4:0] mul_ln71_fu_203_p0;
wire   [6:0] mul_ln71_fu_203_p1;
wire   [10:0] mul_ln71_fu_203_p2;
wire   [1:0] grp_fu_183_p2;
wire   [4:0] add_ln74_fu_223_p2;
wire   [4:0] mul_ln74_fu_232_p0;
wire   [6:0] mul_ln74_fu_232_p1;
wire   [10:0] mul_ln74_fu_232_p2;
wire   [4:0] mul_ln75_fu_265_p0;
wire   [6:0] mul_ln75_fu_265_p1;
wire   [10:0] mul_ln75_fu_265_p2;
wire   [3:0] tmp_5_fu_271_p4;
wire   [15:0] tmp_fu_294_p7;
wire   [15:0] tmp_1_fu_316_p7;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] mul_ln71_fu_203_p00;
wire   [10:0] mul_ln74_fu_232_p00;
wire   [10:0] mul_ln75_fu_265_p00;
wire   [1:0] tmp_fu_294_p1;
wire  signed [1:0] tmp_fu_294_p3;
wire   [1:0] tmp_fu_294_p5;
wire  signed [1:0] tmp_1_fu_316_p1;
wire   [1:0] tmp_1_fu_316_p3;
wire   [1:0] tmp_1_fu_316_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 i_fu_56 = 5'd0;
#0 ap_done_reg = 1'b0;
end

fir_opt4_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_i_1),
    .din1(grp_fu_183_p1),
    .ce(1'b1),
    .dout(grp_fu_183_p2)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U2(
    .din0(mul_ln71_fu_203_p0),
    .din1(mul_ln71_fu_203_p1),
    .dout(mul_ln71_fu_203_p2)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U3(
    .din0(mul_ln74_fu_232_p0),
    .din1(mul_ln74_fu_232_p1),
    .dout(mul_ln74_fu_232_p2)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U4(
    .din0(mul_ln75_fu_265_p0),
    .din1(mul_ln75_fu_265_p1),
    .dout(mul_ln75_fu_265_p2)
);

(* dissolve_hierarchy = "yes" *) fir_opt4_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U5(
    .din0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1),
    .din1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1),
    .din2(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1),
    .def(tmp_fu_294_p7),
    .sel(trunc_ln71_reg_366_pp0_iter9_reg),
    .dout(tmp_fu_294_p9)
);

(* dissolve_hierarchy = "yes" *) fir_opt4_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U6(
    .din0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1),
    .din1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1),
    .din2(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1),
    .def(tmp_1_fu_316_p7),
    .sel(trunc_ln71_reg_366_pp0_iter9_reg),
    .dout(tmp_1_fu_316_p9)
);

fir_opt4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln73_fu_177_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_56 <= add_ln75_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 5'd31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln75_reg_356 <= add_ln75_fu_189_p2;
        add_ln75_reg_356_pp0_iter1_reg <= add_ln75_reg_356;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_1_reg_345 <= ap_sig_allocacmp_i_1;
        i_1_reg_345_pp0_iter1_reg <= i_1_reg_345;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln75_reg_356_pp0_iter2_reg <= add_ln75_reg_356_pp0_iter1_reg;
        add_ln75_reg_356_pp0_iter3_reg <= add_ln75_reg_356_pp0_iter2_reg;
        add_ln75_reg_356_pp0_iter4_reg <= add_ln75_reg_356_pp0_iter3_reg;
        add_ln75_reg_356_pp0_iter5_reg <= add_ln75_reg_356_pp0_iter4_reg;
        add_ln75_reg_356_pp0_iter6_reg <= add_ln75_reg_356_pp0_iter5_reg;
        add_ln75_reg_356_pp0_iter7_reg <= add_ln75_reg_356_pp0_iter6_reg;
        add_ln75_reg_356_pp0_iter8_reg <= add_ln75_reg_356_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383 <= zext_ln74_fu_256_p1;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377 <= zext_ln74_fu_256_p1;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389 <= zext_ln74_fu_256_p1;
        i_1_reg_345_pp0_iter2_reg <= i_1_reg_345_pp0_iter1_reg;
        i_1_reg_345_pp0_iter3_reg <= i_1_reg_345_pp0_iter2_reg;
        i_1_reg_345_pp0_iter4_reg <= i_1_reg_345_pp0_iter3_reg;
        i_1_reg_345_pp0_iter5_reg <= i_1_reg_345_pp0_iter4_reg;
        i_1_reg_345_pp0_iter6_reg <= i_1_reg_345_pp0_iter5_reg;
        i_1_reg_345_pp0_iter7_reg <= i_1_reg_345_pp0_iter6_reg;
        tmp_3_reg_361 <= {{mul_ln71_fu_203_p2[10:7]}};
        tmp_3_reg_361_pp0_iter9_reg <= tmp_3_reg_361;
        tmp_4_reg_372 <= {{mul_ln74_fu_232_p2[10:7]}};
        trunc_ln71_reg_366 <= trunc_ln71_fu_219_p1;
        trunc_ln71_reg_366_pp0_iter9_reg <= trunc_ln71_reg_366;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_177_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd31;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_addr_reg_383;
        end else if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = zext_ln71_fu_288_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln71_reg_366 == 2'd0)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = zext_ln75_fu_281_p1;
        end else if ((trunc_ln71_reg_366 == 2'd2)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = zext_ln74_fu_256_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_reg_366 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_reg_366 == 2'd2)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local = tmp_1_fu_316_p9;
        end else if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local = tmp_fu_294_p9;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = zext_ln71_fu_288_p1;
        end else if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_addr_reg_377;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln71_reg_366 == 2'd2)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = zext_ln75_fu_281_p1;
        end else if ((trunc_ln71_reg_366 == 2'd1)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = zext_ln74_fu_256_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_reg_366 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_reg_366 == 2'd2)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local = tmp_fu_294_p9;
        end else if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local = tmp_1_fu_316_p9;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = zext_ln71_fu_288_p1;
        end else if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_addr_reg_389;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln71_reg_366 == 2'd1)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = zext_ln75_fu_281_p1;
        end else if ((trunc_ln71_reg_366 == 2'd0)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = zext_ln74_fu_256_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_reg_366 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_reg_366 == 2'd0)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local = tmp_fu_294_p9;
        end else if ((trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local = tmp_1_fu_316_p9;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd0) & ~(trunc_ln71_reg_366_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln71_reg_366_pp0_iter9_reg == 2'd0)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln74_fu_223_p2 = ($signed(i_1_reg_345_pp0_iter7_reg) + $signed(5'd31));

assign add_ln75_fu_189_p2 = ($signed(ap_sig_allocacmp_i_1) + $signed(5'd30));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_local;

assign grp_fu_183_p1 = 5'd3;

assign icmp_ln73_fu_177_p2 = ((tmp_2_fu_167_p4 == 4'd0) ? 1'b1 : 1'b0);

assign mul_ln71_fu_203_p0 = mul_ln71_fu_203_p00;

assign mul_ln71_fu_203_p00 = i_1_reg_345_pp0_iter7_reg;

assign mul_ln71_fu_203_p1 = 11'd43;

assign mul_ln74_fu_232_p0 = mul_ln74_fu_232_p00;

assign mul_ln74_fu_232_p00 = add_ln74_fu_223_p2;

assign mul_ln74_fu_232_p1 = 11'd43;

assign mul_ln75_fu_265_p0 = mul_ln75_fu_265_p00;

assign mul_ln75_fu_265_p00 = add_ln75_reg_356_pp0_iter8_reg;

assign mul_ln75_fu_265_p1 = 11'd43;

assign tmp_1_fu_316_p7 = 'bx;

assign tmp_2_fu_167_p4 = {{ap_sig_allocacmp_i_1[4:1]}};

assign tmp_5_fu_271_p4 = {{mul_ln75_fu_265_p2[10:7]}};

assign tmp_fu_294_p7 = 'bx;

assign trunc_ln71_fu_219_p1 = grp_fu_183_p2[1:0];

assign zext_ln71_fu_288_p1 = tmp_3_reg_361_pp0_iter9_reg;

assign zext_ln74_fu_256_p1 = tmp_4_reg_372;

assign zext_ln75_fu_281_p1 = tmp_5_fu_271_p4;

endmodule //fir_opt4_fir_opt4_Pipeline_TDL
