// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_opt4_fir_opt4,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.680000,HLS_SYN_LAT=77,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=805,HLS_SYN_LUT=1282,HLS_VERSION=2025_1_1}" *)

module fir_opt4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dout,
        dout_ap_vld,
        coeffs_address0,
        coeffs_ce0,
        coeffs_q0,
        coeffs_address1,
        coeffs_ce1,
        coeffs_q1,
        din
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] dout;
output   dout_ap_vld;
output  [4:0] coeffs_address0;
output   coeffs_ce0;
input  [15:0] coeffs_q0;
output  [4:0] coeffs_address1;
output   coeffs_ce1;
input  [15:0] coeffs_q1;
input  [15:0] din;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg dout_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0;
wire   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
wire   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0;
wire   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
wire   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0;
wire   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
wire   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_ap_start;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_ap_done;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_ap_idle;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_ap_ready;
wire   [3:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0;
wire   [15:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0;
wire   [3:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
wire   [3:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0;
wire   [15:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0;
wire   [3:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
wire   [3:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0;
wire   [15:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0;
wire   [3:0] grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
wire    grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_ap_start;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_ap_done;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_ap_idle;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_ap_ready;
wire   [4:0] grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address0;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce0;
wire   [4:0] grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address1;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce1;
wire   [15:0] grp_fir_opt4_Pipeline_MAC_fu_85_acc_out;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_acc_out_ap_vld;
wire   [3:0] grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
wire   [3:0] grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
wire   [3:0] grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
wire   [3:0] grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
wire   [3:0] grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
wire   [3:0] grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
wire    grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
reg    grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out;
wire    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out;
reg    grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state4;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;
wire    ap_CS_fsm_state3;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg = 1'b0;
#0 grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg = 1'b0;
end

fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0),
    .ce0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0),
    .we0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0),
    .d0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0),
    .q0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0),
    .address1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1),
    .ce1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1),
    .q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1)
);

fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0),
    .ce0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0),
    .we0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0),
    .d0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0),
    .q0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0),
    .address1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1),
    .ce1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1),
    .q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1)
);

fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0),
    .ce0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0),
    .we0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0),
    .d0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0),
    .q0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0),
    .address1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1),
    .ce1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1),
    .q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1)
);

fir_opt4_fir_opt4_Pipeline_TDL grp_fir_opt4_Pipeline_TDL_fu_75(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_opt4_Pipeline_TDL_fu_75_ap_start),
    .ap_done(grp_fir_opt4_Pipeline_TDL_fu_75_ap_done),
    .ap_idle(grp_fir_opt4_Pipeline_TDL_fu_75_ap_idle),
    .ap_ready(grp_fir_opt4_Pipeline_TDL_fu_75_ap_ready),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1)
);

fir_opt4_fir_opt4_Pipeline_MAC grp_fir_opt4_Pipeline_MAC_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_opt4_Pipeline_MAC_fu_85_ap_start),
    .ap_done(grp_fir_opt4_Pipeline_MAC_fu_85_ap_done),
    .ap_idle(grp_fir_opt4_Pipeline_MAC_fu_85_ap_idle),
    .ap_ready(grp_fir_opt4_Pipeline_MAC_fu_85_ap_ready),
    .coeffs_address0(grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address0),
    .coeffs_ce0(grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce0),
    .coeffs_q0(coeffs_q0),
    .coeffs_address1(grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address1),
    .coeffs_ce1(grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce1),
    .coeffs_q1(coeffs_q1),
    .acc_out(grp_fir_opt4_Pipeline_MAC_fu_85_acc_out),
    .acc_out_ap_vld(grp_fir_opt4_Pipeline_MAC_fu_85_acc_out_ap_vld),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1(grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1),
    .fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_fir_opt4_Pipeline_MAC_fu_85_ap_ready == 1'b1)) begin
            grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg <= 1'b1;
        end else if ((grp_fir_opt4_Pipeline_TDL_fu_75_ap_ready == 1'b1)) begin
            grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fir_opt4_Pipeline_TDL_fu_75_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_opt4_Pipeline_MAC_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        dout_ap_vld = 1'b1;
    end else begin
        dout_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 = 4'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 = (fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 = 4'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 = din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 = (fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 = grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 = grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fir_opt4_Pipeline_TDL_fu_75_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_fir_opt4_Pipeline_MAC_fu_85_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign coeffs_address0 = grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address0;

assign coeffs_address1 = grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address1;

assign coeffs_ce0 = grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce0;

assign coeffs_ce1 = grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce1;

assign dout = grp_fir_opt4_Pipeline_MAC_fu_85_acc_out;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local;

assign grp_fir_opt4_Pipeline_MAC_fu_85_ap_start = grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg;

assign grp_fir_opt4_Pipeline_TDL_fu_75_ap_start = grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg;

endmodule //fir_opt4
