-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_opt4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    dout : OUT STD_LOGIC_VECTOR (15 downto 0);
    dout_ap_vld : OUT STD_LOGIC;
    coeffs_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    coeffs_ce0 : OUT STD_LOGIC;
    coeffs_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    coeffs_ce1 : OUT STD_LOGIC;
    coeffs_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    din : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fir_opt4 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_opt4_fir_opt4,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.680000,HLS_SYN_LAT=77,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=805,HLS_SYN_LUT=1282,HLS_VERSION=2025_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_ap_start : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_ap_done : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_ap_idle : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_ap_ready : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_ap_start : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_ap_done : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_ap_idle : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_ap_ready : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_acc_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_acc_out_ap_vld : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out : STD_LOGIC;
    signal grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_opt4_fir_opt4_Pipeline_TDL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_opt4_fir_opt4_Pipeline_MAC IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        coeffs_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        coeffs_ce0 : OUT STD_LOGIC;
        coeffs_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        coeffs_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        coeffs_ce1 : OUT STD_LOGIC;
        coeffs_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        acc_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_out_ap_vld : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : OUT STD_LOGIC;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_U : component fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 11,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0,
        ce0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0,
        we0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0,
        d0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0,
        q0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0,
        address1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1,
        ce1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1,
        q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1);

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_U : component fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 11,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0,
        ce0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0,
        we0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0,
        d0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0,
        q0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0,
        address1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1,
        ce1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1,
        q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1);

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_U : component fir_opt4_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 11,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0,
        ce0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0,
        we0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0,
        d0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0,
        q0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0,
        address1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1,
        ce1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1,
        q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1);

    grp_fir_opt4_Pipeline_TDL_fu_75 : component fir_opt4_fir_opt4_Pipeline_TDL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fir_opt4_Pipeline_TDL_fu_75_ap_start,
        ap_done => grp_fir_opt4_Pipeline_TDL_fu_75_ap_done,
        ap_idle => grp_fir_opt4_Pipeline_TDL_fu_75_ap_idle,
        ap_ready => grp_fir_opt4_Pipeline_TDL_fu_75_ap_ready,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_d0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 => grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1);

    grp_fir_opt4_Pipeline_MAC_fu_85 : component fir_opt4_fir_opt4_Pipeline_MAC
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fir_opt4_Pipeline_MAC_fu_85_ap_start,
        ap_done => grp_fir_opt4_Pipeline_MAC_fu_85_ap_done,
        ap_idle => grp_fir_opt4_Pipeline_MAC_fu_85_ap_idle,
        ap_ready => grp_fir_opt4_Pipeline_MAC_fu_85_ap_ready,
        coeffs_address0 => grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address0,
        coeffs_ce0 => grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce0,
        coeffs_q0 => coeffs_q0,
        coeffs_address1 => grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address1,
        coeffs_ce1 => grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce1,
        coeffs_q1 => coeffs_q1,
        acc_out => grp_fir_opt4_Pipeline_MAC_fu_85_acc_out,
        acc_out_ap_vld => grp_fir_opt4_Pipeline_MAC_fu_85_acc_out_ap_vld,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 => grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_opt4_Pipeline_MAC_fu_85_ap_ready = ap_const_logic_1)) then 
                    grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_opt4_Pipeline_TDL_fu_75_ap_ready = ap_const_logic_1)) then 
                    grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_fir_opt4_Pipeline_TDL_fu_75_ap_done, grp_fir_opt4_Pipeline_MAC_fu_85_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_fir_opt4_Pipeline_TDL_fu_75_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fir_opt4_Pipeline_MAC_fu_85_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_ap_done)
    begin
        if ((grp_fir_opt4_Pipeline_TDL_fu_75_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_fir_opt4_Pipeline_MAC_fu_85_ap_done)
    begin
        if ((grp_fir_opt4_Pipeline_MAC_fu_85_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    coeffs_address0 <= grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address0;
    coeffs_address1 <= grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_address1;
    coeffs_ce0 <= grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce0;
    coeffs_ce1 <= grp_fir_opt4_Pipeline_MAC_fu_85_coeffs_ce1;
    dout <= grp_fir_opt4_Pipeline_MAC_fu_85_acc_out;

    dout_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            dout_ap_vld <= ap_const_logic_1;
        else 
            dout_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 <= ap_const_lv4_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 <= "XXXX";
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0_assign_proc : process(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0, grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_d0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0, ap_CS_fsm_state2, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0 <= (fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out or ap_const_logic_0);
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_out <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_we0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 <= ap_const_lv4_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 <= "XXXX";
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0_assign_proc : process(din, grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_d0 <= din;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0, ap_CS_fsm_state2, fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0 <= (fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out or ap_const_logic_0);
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_out <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_we0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 <= "XXXX";
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 <= "XXXX";
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1, grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 <= grp_fir_opt4_Pipeline_MAC_fu_85_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0_assign_proc : process(grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 <= grp_fir_opt4_Pipeline_TDL_fu_75_fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fir_opt4_Pipeline_MAC_fu_85_ap_start <= grp_fir_opt4_Pipeline_MAC_fu_85_ap_start_reg;
    grp_fir_opt4_Pipeline_TDL_fu_75_ap_start <= grp_fir_opt4_Pipeline_TDL_fu_75_ap_start_reg;
end behav;
