-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_opt4_fir_opt4_Pipeline_MAC is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    coeffs_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    coeffs_ce0 : OUT STD_LOGIC;
    coeffs_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    coeffs_ce1 : OUT STD_LOGIC;
    coeffs_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 : OUT STD_LOGIC;
    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fir_opt4_fir_opt4_Pipeline_MAC is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv11_2B : STD_LOGIC_VECTOR (10 downto 0) := "00000101011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal tmp_reg_692 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal reg_261 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_reg_684 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_reg_684_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_reg_692_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_692_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln83_fu_303_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln83_reg_696 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln83_reg_696_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_6_reg_703 : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_load_reg_723 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_load_reg_728 : STD_LOGIC_VECTOR (15 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_load_reg_733 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln70_fu_336_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln70_reg_743 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_fu_346_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln70_reg_753 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln70_1_fu_401_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln70_1_reg_785 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln70_2_fu_411_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln70_2_reg_795 : STD_LOGIC_VECTOR (4 downto 0);
    signal coeffs_load_3_reg_830 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal zext_ln70_7_fu_326_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln83_fu_332_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln70_fu_341_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_1_fu_394_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_2_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_4_fu_416_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_3_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln70_5_fu_531_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal acc_fu_82 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_sig_allocacmp_acc_load_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal i_1_fu_86 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln83_fu_293_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local : STD_LOGIC;
    signal fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal coeffs_ce1_local : STD_LOGIC;
    signal coeffs_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal coeffs_ce0_local : STD_LOGIC;
    signal coeffs_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_287_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln70_fu_310_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln70_fu_310_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln70_fu_310_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_287_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_350_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_350_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_350_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln70_1_fu_378_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln70_1_fu_378_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln70_1_fu_378_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_384_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_421_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_421_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln70_2_fu_451_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln70_2_fu_451_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln70_2_fu_451_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_11_fu_457_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_485_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_485_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln70_3_fu_515_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln70_3_fu_515_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln70_3_fu_515_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_12_fu_521_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_538_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_633_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_7_fu_538_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_555_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_555_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_581_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_642_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_8_fu_581_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_598_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_651_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_9_fu_598_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_1_fu_615_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_660_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_633_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_642_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_651_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_660_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln70_1_fu_378_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln70_2_fu_451_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln70_3_fu_515_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln70_fu_310_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_350_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_350_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_350_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_421_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_421_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_421_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_485_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_485_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_485_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_555_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_555_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_555_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component fir_opt4_urem_6ns_3ns_2_10_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component fir_opt4_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component fir_opt4_sparsemux_7_2_16_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_opt4_sparsemux_7_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_opt4_mac_muladd_16s_16s_28ns_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component fir_opt4_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_6ns_3ns_2_10_1_U14 : component fir_opt4_urem_6ns_3ns_2_10_1
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 6,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_sig_allocacmp_i,
        din1 => grp_fu_287_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_287_p2);

    mul_5ns_7ns_11_1_1_U15 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln70_fu_310_p0,
        din1 => mul_ln70_fu_310_p1,
        dout => mul_ln70_fu_310_p2);

    sparsemux_7_2_16_1_1_x_U16 : component fir_opt4_sparsemux_7_2_16_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_load_reg_723,
        din1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_load_reg_728,
        din2 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_load_reg_733,
        def => tmp_2_fu_350_p7,
        sel => tmp_2_fu_350_p8,
        dout => tmp_2_fu_350_p9);

    mul_5ns_7ns_11_1_1_U17 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln70_1_fu_378_p0,
        din1 => mul_ln70_1_fu_378_p1,
        dout => mul_ln70_1_fu_378_p2);

    sparsemux_7_2_16_1_1_U18 : component fir_opt4_sparsemux_7_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 16,
        CASE1 => "10",
        din1_WIDTH => 16,
        CASE2 => "00",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0,
        din1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0,
        din2 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0,
        def => tmp_3_fu_421_p7,
        sel => trunc_ln70_reg_753,
        dout => tmp_3_fu_421_p9);

    mul_5ns_7ns_11_1_1_U19 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln70_2_fu_451_p0,
        din1 => mul_ln70_2_fu_451_p1,
        dout => mul_ln70_2_fu_451_p2);

    sparsemux_7_2_16_1_1_U20 : component fir_opt4_sparsemux_7_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 16,
        CASE1 => "00",
        din1_WIDTH => 16,
        CASE2 => "01",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0,
        din1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0,
        din2 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0,
        def => tmp_4_fu_485_p7,
        sel => trunc_ln70_reg_753,
        dout => tmp_4_fu_485_p9);

    mul_5ns_7ns_11_1_1_U21 : component fir_opt4_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln70_3_fu_515_p0,
        din1 => mul_ln70_3_fu_515_p1,
        dout => mul_ln70_3_fu_515_p2);

    sparsemux_7_2_16_1_1_x_U22 : component fir_opt4_sparsemux_7_2_16_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        din1 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        din2 => fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1,
        def => tmp_5_fu_555_p7,
        sel => trunc_ln70_reg_753,
        dout => tmp_5_fu_555_p9);

    mac_muladd_16s_16s_28ns_28_4_1_U23 : component fir_opt4_mac_muladd_16s_16s_28ns_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => coeffs_q1,
        din1 => tmp_2_fu_350_p9,
        din2 => grp_fu_633_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_633_p3);

    mac_muladd_16s_16s_28ns_28_4_1_U24 : component fir_opt4_mac_muladd_16s_16s_28ns_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_261,
        din1 => tmp_3_fu_421_p9,
        din2 => grp_fu_642_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_642_p3);

    mac_muladd_16s_16s_28ns_28_4_1_U25 : component fir_opt4_mac_muladd_16s_16s_28ns_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_261,
        din1 => tmp_4_fu_485_p9,
        din2 => grp_fu_651_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_651_p3);

    mac_muladd_16s_16s_28ns_28_4_1_U26 : component fir_opt4_mac_muladd_16s_16s_28ns_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => coeffs_load_3_reg_830,
        din1 => tmp_5_fu_555_p9,
        din2 => grp_fu_660_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_660_p3);

    flow_control_loop_pipe_sequential_init_U : component fir_opt4_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                acc_fu_82 <= ap_const_lv16_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                acc_fu_82 <= acc_1_fu_615_p1(27 downto 12);
            end if; 
        end if;
    end process;

    i_1_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_1_fu_86 <= ap_const_lv6_1F;
            elsif (((tmp_reg_692 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                i_1_fu_86 <= add_ln83_fu_293_p2;
            end if; 
        end if;
    end process;

    reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    reg_261 <= coeffs_q1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    reg_261 <= coeffs_q0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln70_1_reg_785 <= add_ln70_1_fu_401_p2;
                add_ln70_2_reg_795 <= add_ln70_2_fu_411_p2;
                trunc_ln70_reg_753 <= trunc_ln70_fu_346_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln70_reg_743 <= add_ln70_fu_336_p2;
                i_reg_684 <= ap_sig_allocacmp_i;
                i_reg_684_pp0_iter1_reg <= i_reg_684;
                tmp_6_reg_703 <= mul_ln70_fu_310_p2(10 downto 7);
                tmp_reg_692 <= ap_sig_allocacmp_i(5 downto 5);
                tmp_reg_692_pp0_iter1_reg <= tmp_reg_692;
                tmp_reg_692_pp0_iter2_reg <= tmp_reg_692_pp0_iter1_reg;
                trunc_ln83_reg_696 <= trunc_ln83_fu_303_p1;
                trunc_ln83_reg_696_pp0_iter2_reg <= trunc_ln83_reg_696;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                coeffs_load_3_reg_830 <= coeffs_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_load_reg_728 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1;
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_load_reg_723 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1;
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_load_reg_733 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to3, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    acc_1_fu_615_p1 <= grp_fu_660_p3;
    acc_out <= acc_fu_82;

    acc_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage3, tmp_reg_692_pp0_iter2_reg, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (tmp_reg_692_pp0_iter2_reg = ap_const_lv1_1))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln70_1_fu_401_p2 <= std_logic_vector(unsigned(trunc_ln83_reg_696_pp0_iter2_reg) + unsigned(ap_const_lv5_1E));
    add_ln70_2_fu_411_p2 <= std_logic_vector(unsigned(trunc_ln83_reg_696_pp0_iter2_reg) + unsigned(ap_const_lv5_1D));
    add_ln70_fu_336_p2 <= std_logic_vector(unsigned(trunc_ln83_reg_696) + unsigned(ap_const_lv5_1F));
    add_ln83_fu_293_p2 <= std_logic_vector(unsigned(i_reg_684) + unsigned(ap_const_lv6_3C));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg, tmp_reg_692)
    begin
        if (((tmp_reg_692 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, acc_fu_82, acc_1_fu_615_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_sig_allocacmp_acc_load_1 <= acc_1_fu_615_p1(27 downto 12);
        else 
            ap_sig_allocacmp_acc_load_1 <= acc_fu_82;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_1_fu_86)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv6_1F;
        else 
            ap_sig_allocacmp_i <= i_1_fu_86;
        end if; 
    end process;

    coeffs_address0 <= coeffs_address0_local;

    coeffs_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage0, zext_ln70_fu_341_p1, zext_ln70_4_fu_416_p1)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                coeffs_address0_local <= zext_ln70_4_fu_416_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                coeffs_address0_local <= zext_ln70_fu_341_p1(5 - 1 downto 0);
            else 
                coeffs_address0_local <= "XXXXX";
            end if;
        else 
            coeffs_address0_local <= "XXXXX";
        end if; 
    end process;

    coeffs_address1 <= coeffs_address1_local;

    coeffs_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln83_fu_332_p1, ap_block_pp0_stage0, zext_ln70_2_fu_406_p1)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                coeffs_address1_local <= zext_ln70_2_fu_406_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                coeffs_address1_local <= zext_ln83_fu_332_p1(5 - 1 downto 0);
            else 
                coeffs_address1_local <= "XXXXX";
            end if;
        else 
            coeffs_address1_local <= "XXXXX";
        end if; 
    end process;

    coeffs_ce0 <= coeffs_ce0_local;

    coeffs_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            coeffs_ce0_local <= ap_const_logic_1;
        else 
            coeffs_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    coeffs_ce1 <= coeffs_ce1_local;

    coeffs_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            coeffs_ce1_local <= ap_const_logic_1;
        else 
            coeffs_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage1, zext_ln70_1_fu_394_p1, zext_ln70_3_fu_467_p1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= zext_ln70_3_fu_467_p1(4 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= zext_ln70_1_fu_394_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, zext_ln70_7_fu_326_p1, ap_block_pp0_stage1, zext_ln70_5_fu_531_p1, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= zext_ln70_5_fu_531_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= zext_ln70_7_fu_326_p1(4 - 1 downto 0);
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage1, zext_ln70_1_fu_394_p1, zext_ln70_3_fu_467_p1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= zext_ln70_3_fu_467_p1(4 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= zext_ln70_1_fu_394_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, zext_ln70_7_fu_326_p1, ap_block_pp0_stage1, zext_ln70_5_fu_531_p1, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= zext_ln70_5_fu_531_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= zext_ln70_7_fu_326_p1(4 - 1 downto 0);
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage1, zext_ln70_1_fu_394_p1, zext_ln70_3_fu_467_p1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= zext_ln70_3_fu_467_p1(4 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= zext_ln70_1_fu_394_p1(4 - 1 downto 0);
            else 
                fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= "XXXX";
            end if;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, zext_ln70_7_fu_326_p1, ap_block_pp0_stage1, zext_ln70_5_fu_531_p1, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= zext_ln70_5_fu_531_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= zext_ln70_7_fu_326_p1(4 - 1 downto 0);
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local <= "XXXX";
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local;

    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local <= ap_const_logic_1;
        else 
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_287_p1 <= ap_const_lv6_3(3 - 1 downto 0);
    grp_fu_633_p2 <= (ap_sig_allocacmp_acc_load_1 & ap_const_lv12_0);
    grp_fu_642_p2 <= (tmp_7_fu_538_p4 & ap_const_lv12_0);
    grp_fu_651_p2 <= (tmp_8_fu_581_p4 & ap_const_lv12_0);
    grp_fu_660_p2 <= (tmp_9_fu_598_p4 & ap_const_lv12_0);
    mul_ln70_1_fu_378_p0 <= mul_ln70_1_fu_378_p00(5 - 1 downto 0);
    mul_ln70_1_fu_378_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_reg_743),11));
    mul_ln70_1_fu_378_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    mul_ln70_2_fu_451_p0 <= mul_ln70_2_fu_451_p00(5 - 1 downto 0);
    mul_ln70_2_fu_451_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_1_reg_785),11));
    mul_ln70_2_fu_451_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    mul_ln70_3_fu_515_p0 <= mul_ln70_3_fu_515_p00(5 - 1 downto 0);
    mul_ln70_3_fu_515_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_2_reg_795),11));
    mul_ln70_3_fu_515_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    mul_ln70_fu_310_p0 <= mul_ln70_fu_310_p00(5 - 1 downto 0);
    mul_ln70_fu_310_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln83_fu_303_p1),11));
    mul_ln70_fu_310_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    tmp_10_fu_384_p4 <= mul_ln70_1_fu_378_p2(10 downto 7);
    tmp_11_fu_457_p4 <= mul_ln70_2_fu_451_p2(10 downto 7);
    tmp_12_fu_521_p4 <= mul_ln70_3_fu_515_p2(10 downto 7);
    tmp_2_fu_350_p7 <= "XXXXXXXXXXXXXXXX";
    tmp_2_fu_350_p8 <= grp_fu_287_p2(2 - 1 downto 0);
    tmp_3_fu_421_p7 <= "XXXXXXXXXXXXXXXX";
    tmp_4_fu_485_p7 <= "XXXXXXXXXXXXXXXX";
    tmp_5_fu_555_p7 <= "XXXXXXXXXXXXXXXX";
    tmp_7_fu_538_p1 <= grp_fu_633_p3;
    tmp_7_fu_538_p4 <= tmp_7_fu_538_p1(27 downto 12);
    tmp_8_fu_581_p1 <= grp_fu_642_p3;
    tmp_8_fu_581_p4 <= tmp_8_fu_581_p1(27 downto 12);
    tmp_9_fu_598_p1 <= grp_fu_651_p3;
    tmp_9_fu_598_p4 <= tmp_9_fu_598_p1(27 downto 12);
    trunc_ln70_fu_346_p1 <= grp_fu_287_p2(2 - 1 downto 0);
    trunc_ln83_fu_303_p1 <= i_reg_684(5 - 1 downto 0);
    zext_ln70_1_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_384_p4),64));
    zext_ln70_2_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_1_fu_401_p2),64));
    zext_ln70_3_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_457_p4),64));
    zext_ln70_4_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_2_fu_411_p2),64));
    zext_ln70_5_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_521_p4),64));
    zext_ln70_7_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_reg_703),64));
    zext_ln70_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_fu_336_p2),64));
    zext_ln83_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_684_pp0_iter1_reg),64));
end behav;
