// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_opt4_fir_opt4_Pipeline_MAC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        coeffs_address0,
        coeffs_ce0,
        coeffs_q0,
        coeffs_address1,
        coeffs_ce1,
        coeffs_q1,
        acc_out,
        acc_out_ap_vld,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1,
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] coeffs_address0;
output   coeffs_ce0;
input  [15:0] coeffs_q0;
output  [4:0] coeffs_address1;
output   coeffs_ce1;
input  [15:0] coeffs_q1;
output  [15:0] acc_out;
output   acc_out_ap_vld;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0;
output  [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1;
output   fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1;
input  [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1;

reg ap_idle;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] tmp_reg_692;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [15:0] reg_261;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] i_reg_684;
reg   [5:0] i_reg_684_pp0_iter1_reg;
reg   [0:0] tmp_reg_692_pp0_iter1_reg;
reg   [0:0] tmp_reg_692_pp0_iter2_reg;
wire   [4:0] trunc_ln83_fu_303_p1;
reg   [4:0] trunc_ln83_reg_696;
reg   [4:0] trunc_ln83_reg_696_pp0_iter2_reg;
reg   [3:0] tmp_6_reg_703;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_load_reg_723;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_load_reg_728;
reg   [15:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_load_reg_733;
wire   [4:0] add_ln70_fu_336_p2;
reg   [4:0] add_ln70_reg_743;
wire   [1:0] trunc_ln70_fu_346_p1;
reg   [1:0] trunc_ln70_reg_753;
wire   [4:0] add_ln70_1_fu_401_p2;
reg   [4:0] add_ln70_1_reg_785;
wire   [4:0] add_ln70_2_fu_411_p2;
reg   [4:0] add_ln70_2_reg_795;
reg  signed [15:0] coeffs_load_3_reg_830;
wire    ap_block_pp0_stage3_11001;
wire   [63:0] zext_ln70_7_fu_326_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln83_fu_332_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln70_fu_341_p1;
wire   [63:0] zext_ln70_1_fu_394_p1;
wire   [63:0] zext_ln70_2_fu_406_p1;
wire   [63:0] zext_ln70_4_fu_416_p1;
wire   [63:0] zext_ln70_3_fu_467_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln70_5_fu_531_p1;
wire    ap_block_pp0_stage3;
reg   [15:0] acc_fu_82;
reg   [15:0] ap_sig_allocacmp_acc_load_1;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [5:0] i_1_fu_86;
wire   [5:0] add_ln83_fu_293_p2;
reg   [5:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage3_01001;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local;
reg    fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local;
reg   [3:0] fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local;
reg    coeffs_ce1_local;
reg   [4:0] coeffs_address1_local;
reg    coeffs_ce0_local;
reg   [4:0] coeffs_address0_local;
wire   [2:0] grp_fu_287_p1;
wire   [4:0] mul_ln70_fu_310_p0;
wire   [6:0] mul_ln70_fu_310_p1;
wire   [10:0] mul_ln70_fu_310_p2;
wire   [1:0] grp_fu_287_p2;
wire   [15:0] tmp_2_fu_350_p7;
wire   [1:0] tmp_2_fu_350_p8;
wire  signed [15:0] tmp_2_fu_350_p9;
wire   [4:0] mul_ln70_1_fu_378_p0;
wire   [6:0] mul_ln70_1_fu_378_p1;
wire   [10:0] mul_ln70_1_fu_378_p2;
wire   [3:0] tmp_10_fu_384_p4;
wire   [15:0] tmp_3_fu_421_p7;
wire  signed [15:0] tmp_3_fu_421_p9;
wire   [4:0] mul_ln70_2_fu_451_p0;
wire   [6:0] mul_ln70_2_fu_451_p1;
wire   [10:0] mul_ln70_2_fu_451_p2;
wire   [3:0] tmp_11_fu_457_p4;
wire   [15:0] tmp_4_fu_485_p7;
wire  signed [15:0] tmp_4_fu_485_p9;
wire   [4:0] mul_ln70_3_fu_515_p0;
wire   [6:0] mul_ln70_3_fu_515_p1;
wire   [10:0] mul_ln70_3_fu_515_p2;
wire   [3:0] tmp_12_fu_521_p4;
wire  signed [27:0] tmp_7_fu_538_p1;
wire   [27:0] grp_fu_633_p3;
wire   [15:0] tmp_7_fu_538_p4;
wire   [15:0] tmp_5_fu_555_p7;
wire  signed [15:0] tmp_5_fu_555_p9;
wire  signed [27:0] tmp_8_fu_581_p1;
wire   [27:0] grp_fu_642_p3;
wire   [15:0] tmp_8_fu_581_p4;
wire  signed [27:0] tmp_9_fu_598_p1;
wire   [27:0] grp_fu_651_p3;
wire   [15:0] tmp_9_fu_598_p4;
wire  signed [27:0] acc_1_fu_615_p1;
wire   [27:0] grp_fu_660_p3;
wire   [27:0] grp_fu_633_p2;
wire   [27:0] grp_fu_642_p2;
wire   [27:0] grp_fu_651_p2;
wire   [27:0] grp_fu_660_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to3;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] mul_ln70_1_fu_378_p00;
wire   [10:0] mul_ln70_2_fu_451_p00;
wire   [10:0] mul_ln70_3_fu_515_p00;
wire   [10:0] mul_ln70_fu_310_p00;
wire   [1:0] tmp_2_fu_350_p1;
wire   [1:0] tmp_2_fu_350_p3;
wire  signed [1:0] tmp_2_fu_350_p5;
wire   [1:0] tmp_3_fu_421_p1;
wire  signed [1:0] tmp_3_fu_421_p3;
wire   [1:0] tmp_3_fu_421_p5;
wire  signed [1:0] tmp_4_fu_485_p1;
wire   [1:0] tmp_4_fu_485_p3;
wire   [1:0] tmp_4_fu_485_p5;
wire   [1:0] tmp_5_fu_555_p1;
wire   [1:0] tmp_5_fu_555_p3;
wire  signed [1:0] tmp_5_fu_555_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 acc_fu_82 = 16'd0;
#0 i_1_fu_86 = 6'd0;
#0 ap_done_reg = 1'b0;
end

fir_opt4_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_i),
    .din1(grp_fu_287_p1),
    .ce(1'b1),
    .dout(grp_fu_287_p2)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U15(
    .din0(mul_ln70_fu_310_p0),
    .din1(mul_ln70_fu_310_p1),
    .dout(mul_ln70_fu_310_p2)
);

(* dissolve_hierarchy = "yes" *) fir_opt4_sparsemux_7_2_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_x_U16(
    .din0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_load_reg_723),
    .din1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_load_reg_728),
    .din2(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_load_reg_733),
    .def(tmp_2_fu_350_p7),
    .sel(tmp_2_fu_350_p8),
    .dout(tmp_2_fu_350_p9)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U17(
    .din0(mul_ln70_1_fu_378_p0),
    .din1(mul_ln70_1_fu_378_p1),
    .dout(mul_ln70_1_fu_378_p2)
);

(* dissolve_hierarchy = "yes" *) fir_opt4_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U18(
    .din0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0),
    .din1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0),
    .din2(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0),
    .def(tmp_3_fu_421_p7),
    .sel(trunc_ln70_reg_753),
    .dout(tmp_3_fu_421_p9)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U19(
    .din0(mul_ln70_2_fu_451_p0),
    .din1(mul_ln70_2_fu_451_p1),
    .dout(mul_ln70_2_fu_451_p2)
);

(* dissolve_hierarchy = "yes" *) fir_opt4_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U20(
    .din0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q0),
    .din1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q0),
    .din2(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q0),
    .def(tmp_4_fu_485_p7),
    .sel(trunc_ln70_reg_753),
    .dout(tmp_4_fu_485_p9)
);

fir_opt4_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U21(
    .din0(mul_ln70_3_fu_515_p0),
    .din1(mul_ln70_3_fu_515_p1),
    .dout(mul_ln70_3_fu_515_p2)
);

(* dissolve_hierarchy = "yes" *) fir_opt4_sparsemux_7_2_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_x_U22(
    .din0(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1),
    .din1(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1),
    .din2(fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1),
    .def(tmp_5_fu_555_p7),
    .sel(trunc_ln70_reg_753),
    .dout(tmp_5_fu_555_p9)
);

fir_opt4_mac_muladd_16s_16s_28ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28ns_28_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(coeffs_q1),
    .din1(tmp_2_fu_350_p9),
    .din2(grp_fu_633_p2),
    .ce(1'b1),
    .dout(grp_fu_633_p3)
);

fir_opt4_mac_muladd_16s_16s_28ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28ns_28_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_261),
    .din1(tmp_3_fu_421_p9),
    .din2(grp_fu_642_p2),
    .ce(1'b1),
    .dout(grp_fu_642_p3)
);

fir_opt4_mac_muladd_16s_16s_28ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28ns_28_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_261),
    .din1(tmp_4_fu_485_p9),
    .din2(grp_fu_651_p2),
    .ce(1'b1),
    .dout(grp_fu_651_p3)
);

fir_opt4_mac_muladd_16s_16s_28ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28ns_28_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(coeffs_load_3_reg_830),
    .din1(tmp_5_fu_555_p9),
    .din2(grp_fu_660_p2),
    .ce(1'b1),
    .dout(grp_fu_660_p3)
);

fir_opt4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_fu_82 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_fu_82 <= {{acc_1_fu_615_p1[27:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_fu_86 <= 6'd31;
    end else if (((tmp_reg_692 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        i_1_fu_86 <= add_ln83_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            reg_261 <= coeffs_q1;
        end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_261 <= coeffs_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln70_1_reg_785 <= add_ln70_1_fu_401_p2;
        add_ln70_2_reg_795 <= add_ln70_2_fu_411_p2;
        trunc_ln70_reg_753 <= trunc_ln70_fu_346_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln70_reg_743 <= add_ln70_fu_336_p2;
        i_reg_684 <= ap_sig_allocacmp_i;
        i_reg_684_pp0_iter1_reg <= i_reg_684;
        tmp_6_reg_703 <= {{mul_ln70_fu_310_p2[10:7]}};
        tmp_reg_692 <= ap_sig_allocacmp_i[32'd5];
        tmp_reg_692_pp0_iter1_reg <= tmp_reg_692;
        tmp_reg_692_pp0_iter2_reg <= tmp_reg_692_pp0_iter1_reg;
        trunc_ln83_reg_696 <= trunc_ln83_fu_303_p1;
        trunc_ln83_reg_696_pp0_iter2_reg <= trunc_ln83_reg_696;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        coeffs_load_3_reg_830 <= coeffs_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_load_reg_728 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_q1;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_load_reg_723 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_q1;
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_load_reg_733 <= fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (tmp_reg_692_pp0_iter2_reg == 1'd1))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_692 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_acc_load_1 = {{acc_1_fu_615_p1[27:12]}};
    end else begin
        ap_sig_allocacmp_acc_load_1 = acc_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 6'd31;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_86;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            coeffs_address0_local = zext_ln70_4_fu_416_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            coeffs_address0_local = zext_ln70_fu_341_p1;
        end else begin
            coeffs_address0_local = 'bx;
        end
    end else begin
        coeffs_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            coeffs_address1_local = zext_ln70_2_fu_406_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            coeffs_address1_local = zext_ln83_fu_332_p1;
        end else begin
            coeffs_address1_local = 'bx;
        end
    end else begin
        coeffs_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        coeffs_ce0_local = 1'b1;
    end else begin
        coeffs_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        coeffs_ce1_local = 1'b1;
    end else begin
        coeffs_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = zext_ln70_3_fu_467_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = zext_ln70_1_fu_394_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = zext_ln70_5_fu_531_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = zext_ln70_7_fu_326_p1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = zext_ln70_3_fu_467_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = zext_ln70_1_fu_394_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = zext_ln70_5_fu_531_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = zext_ln70_7_fu_326_p1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = zext_ln70_3_fu_467_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = zext_ln70_1_fu_394_p1;
        end else begin
            fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = 'bx;
        end
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = zext_ln70_5_fu_531_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = zext_ln70_7_fu_326_p1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local = 1'b1;
    end else begin
        fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_615_p1 = grp_fu_660_p3;

assign acc_out = acc_fu_82;

assign add_ln70_1_fu_401_p2 = ($signed(trunc_ln83_reg_696_pp0_iter2_reg) + $signed(5'd30));

assign add_ln70_2_fu_411_p2 = ($signed(trunc_ln83_reg_696_pp0_iter2_reg) + $signed(5'd29));

assign add_ln70_fu_336_p2 = ($signed(trunc_ln83_reg_696) + $signed(5'd31));

assign add_ln83_fu_293_p2 = ($signed(i_reg_684) + $signed(6'd60));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign coeffs_address0 = coeffs_address0_local;

assign coeffs_address1 = coeffs_address1_local;

assign coeffs_ce0 = coeffs_ce0_local;

assign coeffs_ce1 = coeffs_ce1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_address1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_1_ce1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_address1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_2_ce1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_address1_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce0_local;

assign fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1 = fir_opt4_ap_fixed_ap_fixed_ap_fixed_16_4_5_3_0_shift_reg_ce1_local;

assign grp_fu_287_p1 = 6'd3;

assign grp_fu_633_p2 = {{ap_sig_allocacmp_acc_load_1}, {12'd0}};

assign grp_fu_642_p2 = {{tmp_7_fu_538_p4}, {12'd0}};

assign grp_fu_651_p2 = {{tmp_8_fu_581_p4}, {12'd0}};

assign grp_fu_660_p2 = {{tmp_9_fu_598_p4}, {12'd0}};

assign mul_ln70_1_fu_378_p0 = mul_ln70_1_fu_378_p00;

assign mul_ln70_1_fu_378_p00 = add_ln70_reg_743;

assign mul_ln70_1_fu_378_p1 = 11'd43;

assign mul_ln70_2_fu_451_p0 = mul_ln70_2_fu_451_p00;

assign mul_ln70_2_fu_451_p00 = add_ln70_1_reg_785;

assign mul_ln70_2_fu_451_p1 = 11'd43;

assign mul_ln70_3_fu_515_p0 = mul_ln70_3_fu_515_p00;

assign mul_ln70_3_fu_515_p00 = add_ln70_2_reg_795;

assign mul_ln70_3_fu_515_p1 = 11'd43;

assign mul_ln70_fu_310_p0 = mul_ln70_fu_310_p00;

assign mul_ln70_fu_310_p00 = trunc_ln83_fu_303_p1;

assign mul_ln70_fu_310_p1 = 11'd43;

assign tmp_10_fu_384_p4 = {{mul_ln70_1_fu_378_p2[10:7]}};

assign tmp_11_fu_457_p4 = {{mul_ln70_2_fu_451_p2[10:7]}};

assign tmp_12_fu_521_p4 = {{mul_ln70_3_fu_515_p2[10:7]}};

assign tmp_2_fu_350_p7 = 'bx;

assign tmp_2_fu_350_p8 = grp_fu_287_p2[1:0];

assign tmp_3_fu_421_p7 = 'bx;

assign tmp_4_fu_485_p7 = 'bx;

assign tmp_5_fu_555_p7 = 'bx;

assign tmp_7_fu_538_p1 = grp_fu_633_p3;

assign tmp_7_fu_538_p4 = {{tmp_7_fu_538_p1[27:12]}};

assign tmp_8_fu_581_p1 = grp_fu_642_p3;

assign tmp_8_fu_581_p4 = {{tmp_8_fu_581_p1[27:12]}};

assign tmp_9_fu_598_p1 = grp_fu_651_p3;

assign tmp_9_fu_598_p4 = {{tmp_9_fu_598_p1[27:12]}};

assign trunc_ln70_fu_346_p1 = grp_fu_287_p2[1:0];

assign trunc_ln83_fu_303_p1 = i_reg_684[4:0];

assign zext_ln70_1_fu_394_p1 = tmp_10_fu_384_p4;

assign zext_ln70_2_fu_406_p1 = add_ln70_1_fu_401_p2;

assign zext_ln70_3_fu_467_p1 = tmp_11_fu_457_p4;

assign zext_ln70_4_fu_416_p1 = add_ln70_2_fu_411_p2;

assign zext_ln70_5_fu_531_p1 = tmp_12_fu_521_p4;

assign zext_ln70_7_fu_326_p1 = tmp_6_reg_703;

assign zext_ln70_fu_341_p1 = add_ln70_fu_336_p2;

assign zext_ln83_fu_332_p1 = i_reg_684_pp0_iter1_reg;

endmodule //fir_opt4_fir_opt4_Pipeline_MAC
